# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               NoClouds
tagline:             'The NoClouds Organization on Github'
description:         'Your source for information and updates on the NoClouds developent project on Github.'
url:                 https://noclouds.github.io/lanyon_homepage
baseurl:             '/lanyon_homepage'
paginate:            5

# About/contact
author:
  name:              Isaac Jacobs
  url:               NoClouds.xyz
  email:             everforward@live.com

# Custom vars
version:             1.0.0
